### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by denizekiz** [mkmoore7/Gesture#1]
Hi it would be better if you could add timestamp for sensors. :)

**Comment by mkmoore7** [comment]
On a certain level, I agree and plan to add this feature soon.

However Myo samples at a consistent rate, so the timestamps can be inferred from the data. The EMG arrays sample at a rate of 200 hz (or every 5 ms) and the inertial measurement unit (IMU) (including the gyroscope and accelerometer readings (and the orientation vectors)), sample at 50 hz (one sample every 20 ms). Using these you can calculate any timestamp necessary.

Hope this helps.
